version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/db
      - RABBITMQ_URL=amqp://rabbitmq_user:rabbitmq_password@rabbitmq:5672
    depends_on:
      - postgres_db
      - rabbitmq

  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=rabbitmq_password
      - RABBITMQ_DEFAULT_VHOST=/test

volumes:
  postgres_data:
